#############################################################################
# Makefile for building: MLP
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  ./MLP.pro
# Template: app
# Command: /home/leonard/Qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=release -o Makefile ./MLP.pro
#############################################################################

MAKEFILE      = Makefile
ARCH 	      = corei7
GCC_DIR	      = /home/leonard/Qt/5.5/gcc_64/mkspecs/

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNDEBUG -DEIGEN_USE_MKL_ALL
CFLAGS        = -pipe -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=$(ARCH) -openmp -static -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I./Eigen -I/opt/intel/mkl/include -I$(GCC_DIR)linux-g++
LINK          = g++
#LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/leonard/Qt/5.5/gcc_64
LIBS          = $(SUBLIBS) -L/opt/intel/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -L/opt/intel/lib/intel64 -liomp5 -lpthread -lm -L./Eigen -leigen
#AR            = ar cqs
#RANLIB        = 
#SED           = sed
#STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ./main.cpp \
		./multilayerperceptron.cpp 
OBJECTS       = main.o \
		multilayerperceptron.o

TARGET        = MLP


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)


all: Makefile $(TARGET)

clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: ./main.cpp ./multilayerperceptron.h \
		./includes.h \
		./Eigen/Dense \
		./Eigen/Core \
		./Eigen/src/Core/util/DisableStupidWarnings.h \
		./Eigen/src/Core/util/Macros.h \
		./Eigen/src/Core/util/MKL_support.h \
		/opt/intel/mkl/include/mkl.h \
		/opt/intel/mkl/include/mkl_types.h \
		/opt/intel/mkl/include/mkl_blas.h \
		/opt/intel/mkl/include/mkl_trans.h \
		/opt/intel/mkl/include/mkl_cblas.h \
		/opt/intel/mkl/include/mkl_spblas.h \
		/opt/intel/mkl/include/mkl_lapack.h \
		/opt/intel/mkl/include/mkl_lapacke.h \
		/opt/intel/mkl/include/mkl_solver.h \
		/opt/intel/mkl/include/mkl_dss.h \
		/opt/intel/mkl/include/mkl_pardiso.h \
		/opt/intel/mkl/include/mkl_sparse_handle.h \
		/opt/intel/mkl/include/mkl_rci.h \
		/opt/intel/mkl/include/mkl_service.h \
		/opt/intel/mkl/include/mkl_vml.h \
		/opt/intel/mkl/include/mkl_vml_defines.h \
		/opt/intel/mkl/include/mkl_vml_types.h \
		/opt/intel/mkl/include/mkl_vml_functions.h \
		/opt/intel/mkl/include/mkl_vsl.h \
		/opt/intel/mkl/include/mkl_vsl_defines.h \
		/opt/intel/mkl/include/mkl_vsl_functions.h \
		/opt/intel/mkl/include/mkl_vsl_types.h \
		/opt/intel/mkl/include/mkl_df.h \
		/opt/intel/mkl/include/mkl_df_defines.h \
		/opt/intel/mkl/include/mkl_df_functions.h \
		/opt/intel/mkl/include/mkl_df_types.h \
		/opt/intel/mkl/include/mkl_dfti.h \
		/opt/intel/mkl/include/mkl_trig_transforms.h \
		/opt/intel/mkl/include/mkl_poisson.h \
		/opt/intel/mkl/include/mkl_solvers_ee.h \
		/opt/intel/mkl/include/mkl_direct_call.h \
		/opt/intel/mkl/include/mkl_direct_blas.h \
		./Eigen/src/Core/util/Constants.h \
		./Eigen/src/Core/util/ForwardDeclarations.h \
		./Eigen/src/Core/util/Meta.h \
		./Eigen/src/Core/util/StaticAssert.h \
		./Eigen/src/Core/util/XprHelper.h \
		./Eigen/src/Core/util/Memory.h \
		./Eigen/src/Core/NumTraits.h \
		./Eigen/src/Core/MathFunctions.h \
		./Eigen/src/Core/GenericPacketMath.h \
		./Eigen/src/Core/arch/SSE/PacketMath.h \
		./Eigen/src/Core/arch/SSE/MathFunctions.h \
		./Eigen/src/Core/arch/SSE/Complex.h \
		./Eigen/src/Core/arch/AltiVec/PacketMath.h \
		./Eigen/src/Core/arch/AltiVec/Complex.h \
		./Eigen/src/Core/arch/NEON/PacketMath.h \
		./Eigen/src/Core/arch/NEON/Complex.h \
		./Eigen/src/Core/arch/Default/Settings.h \
		./Eigen/src/Core/Functors.h \
		./Eigen/src/Core/DenseCoeffsBase.h \
		./Eigen/src/Core/DenseBase.h \
		./Eigen/src/plugins/BlockMethods.h \
		./Eigen/src/Core/MatrixBase.h \
		./Eigen/src/plugins/CommonCwiseUnaryOps.h \
		./Eigen/src/plugins/CommonCwiseBinaryOps.h \
		./Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		./Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		./Eigen/src/Core/EigenBase.h \
		./Eigen/src/Core/Assign.h \
		./Eigen/src/Core/util/BlasUtil.h \
		./Eigen/src/Core/DenseStorage.h \
		./Eigen/src/Core/NestByValue.h \
		./Eigen/src/Core/ForceAlignedAccess.h \
		./Eigen/src/Core/ReturnByValue.h \
		./Eigen/src/Core/NoAlias.h \
		./Eigen/src/Core/PlainObjectBase.h \
		./Eigen/src/Core/Matrix.h \
		./Eigen/src/Core/Array.h \
		./Eigen/src/Core/CwiseBinaryOp.h \
		./Eigen/src/Core/CwiseUnaryOp.h \
		./Eigen/src/Core/CwiseNullaryOp.h \
		./Eigen/src/Core/CwiseUnaryView.h \
		./Eigen/src/Core/SelfCwiseBinaryOp.h \
		./Eigen/src/Core/Dot.h \
		./Eigen/src/Core/StableNorm.h \
		./Eigen/src/Core/MapBase.h \
		./Eigen/src/Core/Stride.h \
		./Eigen/src/Core/Map.h \
		./Eigen/src/Core/Block.h \
		./Eigen/src/Core/VectorBlock.h \
		./Eigen/src/Core/Ref.h \
		./Eigen/src/Core/Transpose.h \
		./Eigen/src/Core/DiagonalMatrix.h \
		./Eigen/src/Core/Diagonal.h \
		./Eigen/src/Core/DiagonalProduct.h \
		./Eigen/src/Core/PermutationMatrix.h \
		./Eigen/src/Core/Transpositions.h \
		./Eigen/src/Core/Redux.h \
		./Eigen/src/Core/Visitor.h \
		./Eigen/src/Core/Fuzzy.h \
		./Eigen/src/Core/IO.h \
		./Eigen/src/Core/Swap.h \
		./Eigen/src/Core/CommaInitializer.h \
		./Eigen/src/Core/Flagged.h \
		./Eigen/src/Core/ProductBase.h \
		./Eigen/src/Core/GeneralProduct.h \
		./Eigen/src/Core/TriangularMatrix.h \
		./Eigen/src/Core/SelfAdjointView.h \
		./Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		./Eigen/src/Core/products/Parallelizer.h \
		./Eigen/src/Core/products/CoeffBasedProduct.h \
		./Eigen/src/Core/products/GeneralMatrixVector.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix.h \
		./Eigen/src/Core/SolveTriangular.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		./Eigen/src/Core/products/SelfadjointProduct.h \
		./Eigen/src/Core/products/SelfadjointRank2Update.h \
		./Eigen/src/Core/products/TriangularMatrixVector.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix.h \
		./Eigen/src/Core/products/TriangularSolverMatrix.h \
		./Eigen/src/Core/products/TriangularSolverVector.h \
		./Eigen/src/Core/BandMatrix.h \
		./Eigen/src/Core/CoreIterators.h \
		./Eigen/src/Core/BooleanRedux.h \
		./Eigen/src/Core/Select.h \
		./Eigen/src/Core/VectorwiseOp.h \
		./Eigen/src/Core/Random.h \
		./Eigen/src/Core/Replicate.h \
		./Eigen/src/Core/Reverse.h \
		./Eigen/src/Core/ArrayBase.h \
		./Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		./Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		./Eigen/src/Core/ArrayWrapper.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		./Eigen/src/Core/Assign_MKL.h \
		./Eigen/src/Core/GlobalFunctions.h \
		./Eigen/src/Core/util/ReenableStupidWarnings.h \
		./Eigen/Eigen2Support \
		./Eigen/src/Eigen2Support/Macros.h \
		./Eigen/src/Eigen2Support/Memory.h \
		./Eigen/src/Eigen2Support/Meta.h \
		./Eigen/src/Eigen2Support/Lazy.h \
		./Eigen/src/Eigen2Support/Cwise.h \
		./Eigen/src/Eigen2Support/CwiseOperators.h \
		./Eigen/src/Eigen2Support/TriangularSolver.h \
		./Eigen/src/Eigen2Support/Block.h \
		./Eigen/src/Eigen2Support/VectorBlock.h \
		./Eigen/src/Eigen2Support/Minor.h \
		./Eigen/src/Eigen2Support/MathFunctions.h \
		./Eigen/LU \
		./Eigen/src/misc/Solve.h \
		./Eigen/src/misc/Kernel.h \
		./Eigen/src/misc/Image.h \
		./Eigen/src/LU/FullPivLU.h \
		./Eigen/src/LU/PartialPivLU.h \
		./Eigen/src/LU/PartialPivLU_MKL.h \
		./Eigen/src/LU/Determinant.h \
		./Eigen/src/LU/Inverse.h \
		./Eigen/src/LU/arch/Inverse_SSE.h \
		./Eigen/src/Eigen2Support/LU.h \
		./Eigen/Cholesky \
		./Eigen/src/Cholesky/LLT.h \
		./Eigen/src/Cholesky/LDLT.h \
		./Eigen/src/Cholesky/LLT_MKL.h \
		./Eigen/QR \
		./Eigen/Jacobi \
		./Eigen/src/Jacobi/Jacobi.h \
		./Eigen/Householder \
		./Eigen/src/Householder/Householder.h \
		./Eigen/src/Householder/HouseholderSequence.h \
		./Eigen/src/Householder/BlockHouseholder.h \
		./Eigen/src/QR/HouseholderQR.h \
		./Eigen/src/QR/FullPivHouseholderQR.h \
		./Eigen/src/QR/ColPivHouseholderQR.h \
		./Eigen/src/QR/HouseholderQR_MKL.h \
		./Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		./Eigen/src/Eigen2Support/QR.h \
		./Eigen/Eigenvalues \
		./Eigen/Geometry \
		./Eigen/SVD \
		./Eigen/src/SVD/JacobiSVD.h \
		./Eigen/src/SVD/JacobiSVD_MKL.h \
		./Eigen/src/SVD/UpperBidiagonalization.h \
		./Eigen/src/Eigen2Support/SVD.h \
		./Eigen/src/Geometry/OrthoMethods.h \
		./Eigen/src/Geometry/EulerAngles.h \
		./Eigen/src/Geometry/Homogeneous.h \
		./Eigen/src/Geometry/RotationBase.h \
		./Eigen/src/Geometry/Rotation2D.h \
		./Eigen/src/Geometry/Quaternion.h \
		./Eigen/src/Geometry/AngleAxis.h \
		./Eigen/src/Geometry/Transform.h \
		./Eigen/src/Geometry/Translation.h \
		./Eigen/src/Geometry/Scaling.h \
		./Eigen/src/Geometry/Hyperplane.h \
		./Eigen/src/Geometry/ParametrizedLine.h \
		./Eigen/src/Geometry/AlignedBox.h \
		./Eigen/src/Geometry/Umeyama.h \
		./Eigen/src/Geometry/arch/Geometry_SSE.h \
		./Eigen/src/Eigen2Support/Geometry/All.h \
		./Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		./Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		./Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		./Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		./Eigen/src/Eigen2Support/Geometry/Transform.h \
		./Eigen/src/Eigen2Support/Geometry/Translation.h \
		./Eigen/src/Eigen2Support/Geometry/Scaling.h \
		./Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		./Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		./Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		./Eigen/src/Eigenvalues/Tridiagonalization.h \
		./Eigen/src/Eigenvalues/RealSchur.h \
		./Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		./Eigen/src/Eigenvalues/EigenSolver.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/ComplexSchur.h \
		./Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		./Eigen/src/Eigenvalues/RealQZ.h \
		./Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		./Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		./Eigen/src/Eigenvalues/RealSchur_MKL.h \
		./Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h \
		./io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ./main.cpp

multilayerperceptron.o: ./multilayerperceptron.cpp ./multilayerperceptron.h \
		./includes.h \
		./Eigen/Dense \
		./Eigen/Core \
		./Eigen/src/Core/util/DisableStupidWarnings.h \
		./Eigen/src/Core/util/Macros.h \
		./Eigen/src/Core/util/MKL_support.h \
		/opt/intel/mkl/include/mkl.h \
		/opt/intel/mkl/include/mkl_types.h \
		/opt/intel/mkl/include/mkl_blas.h \
		/opt/intel/mkl/include/mkl_trans.h \
		/opt/intel/mkl/include/mkl_cblas.h \
		/opt/intel/mkl/include/mkl_spblas.h \
		/opt/intel/mkl/include/mkl_lapack.h \
		/opt/intel/mkl/include/mkl_lapacke.h \
		/opt/intel/mkl/include/mkl_solver.h \
		/opt/intel/mkl/include/mkl_dss.h \
		/opt/intel/mkl/include/mkl_pardiso.h \
		/opt/intel/mkl/include/mkl_sparse_handle.h \
		/opt/intel/mkl/include/mkl_rci.h \
		/opt/intel/mkl/include/mkl_service.h \
		/opt/intel/mkl/include/mkl_vml.h \
		/opt/intel/mkl/include/mkl_vml_defines.h \
		/opt/intel/mkl/include/mkl_vml_types.h \
		/opt/intel/mkl/include/mkl_vml_functions.h \
		/opt/intel/mkl/include/mkl_vsl.h \
		/opt/intel/mkl/include/mkl_vsl_defines.h \
		/opt/intel/mkl/include/mkl_vsl_functions.h \
		/opt/intel/mkl/include/mkl_vsl_types.h \
		/opt/intel/mkl/include/mkl_df.h \
		/opt/intel/mkl/include/mkl_df_defines.h \
		/opt/intel/mkl/include/mkl_df_functions.h \
		/opt/intel/mkl/include/mkl_df_types.h \
		/opt/intel/mkl/include/mkl_dfti.h \
		/opt/intel/mkl/include/mkl_trig_transforms.h \
		/opt/intel/mkl/include/mkl_poisson.h \
		/opt/intel/mkl/include/mkl_solvers_ee.h \
		/opt/intel/mkl/include/mkl_direct_call.h \
		/opt/intel/mkl/include/mkl_direct_blas.h \
		./Eigen/src/Core/util/Constants.h \
		./Eigen/src/Core/util/ForwardDeclarations.h \
		./Eigen/src/Core/util/Meta.h \
		./Eigen/src/Core/util/StaticAssert.h \
		./Eigen/src/Core/util/XprHelper.h \
		./Eigen/src/Core/util/Memory.h \
		./Eigen/src/Core/NumTraits.h \
		./Eigen/src/Core/MathFunctions.h \
		./Eigen/src/Core/GenericPacketMath.h \
		./Eigen/src/Core/arch/SSE/PacketMath.h \
		./Eigen/src/Core/arch/SSE/MathFunctions.h \
		./Eigen/src/Core/arch/SSE/Complex.h \
		./Eigen/src/Core/arch/AltiVec/PacketMath.h \
		./Eigen/src/Core/arch/AltiVec/Complex.h \
		./Eigen/src/Core/arch/NEON/PacketMath.h \
		./Eigen/src/Core/arch/NEON/Complex.h \
		./Eigen/src/Core/arch/Default/Settings.h \
		./Eigen/src/Core/Functors.h \
		./Eigen/src/Core/DenseCoeffsBase.h \
		./Eigen/src/Core/DenseBase.h \
		./Eigen/src/plugins/BlockMethods.h \
		./Eigen/src/Core/MatrixBase.h \
		./Eigen/src/plugins/CommonCwiseUnaryOps.h \
		./Eigen/src/plugins/CommonCwiseBinaryOps.h \
		./Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		./Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		./Eigen/src/Core/EigenBase.h \
		./Eigen/src/Core/Assign.h \
		./Eigen/src/Core/util/BlasUtil.h \
		./Eigen/src/Core/DenseStorage.h \
		./Eigen/src/Core/NestByValue.h \
		./Eigen/src/Core/ForceAlignedAccess.h \
		./Eigen/src/Core/ReturnByValue.h \
		./Eigen/src/Core/NoAlias.h \
		./Eigen/src/Core/PlainObjectBase.h \
		./Eigen/src/Core/Matrix.h \
		./Eigen/src/Core/Array.h \
		./Eigen/src/Core/CwiseBinaryOp.h \
		./Eigen/src/Core/CwiseUnaryOp.h \
		./Eigen/src/Core/CwiseNullaryOp.h \
		./Eigen/src/Core/CwiseUnaryView.h \
		./Eigen/src/Core/SelfCwiseBinaryOp.h \
		./Eigen/src/Core/Dot.h \
		./Eigen/src/Core/StableNorm.h \
		./Eigen/src/Core/MapBase.h \
		./Eigen/src/Core/Stride.h \
		./Eigen/src/Core/Map.h \
		./Eigen/src/Core/Block.h \
		./Eigen/src/Core/VectorBlock.h \
		./Eigen/src/Core/Ref.h \
		./Eigen/src/Core/Transpose.h \
		./Eigen/src/Core/DiagonalMatrix.h \
		./Eigen/src/Core/Diagonal.h \
		./Eigen/src/Core/DiagonalProduct.h \
		./Eigen/src/Core/PermutationMatrix.h \
		./Eigen/src/Core/Transpositions.h \
		./Eigen/src/Core/Redux.h \
		./Eigen/src/Core/Visitor.h \
		./Eigen/src/Core/Fuzzy.h \
		./Eigen/src/Core/IO.h \
		./Eigen/src/Core/Swap.h \
		./Eigen/src/Core/CommaInitializer.h \
		./Eigen/src/Core/Flagged.h \
		./Eigen/src/Core/ProductBase.h \
		./Eigen/src/Core/GeneralProduct.h \
		./Eigen/src/Core/TriangularMatrix.h \
		./Eigen/src/Core/SelfAdjointView.h \
		./Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		./Eigen/src/Core/products/Parallelizer.h \
		./Eigen/src/Core/products/CoeffBasedProduct.h \
		./Eigen/src/Core/products/GeneralMatrixVector.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix.h \
		./Eigen/src/Core/SolveTriangular.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		./Eigen/src/Core/products/SelfadjointProduct.h \
		./Eigen/src/Core/products/SelfadjointRank2Update.h \
		./Eigen/src/Core/products/TriangularMatrixVector.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix.h \
		./Eigen/src/Core/products/TriangularSolverMatrix.h \
		./Eigen/src/Core/products/TriangularSolverVector.h \
		./Eigen/src/Core/BandMatrix.h \
		./Eigen/src/Core/CoreIterators.h \
		./Eigen/src/Core/BooleanRedux.h \
		./Eigen/src/Core/Select.h \
		./Eigen/src/Core/VectorwiseOp.h \
		./Eigen/src/Core/Random.h \
		./Eigen/src/Core/Replicate.h \
		./Eigen/src/Core/Reverse.h \
		./Eigen/src/Core/ArrayBase.h \
		./Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		./Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		./Eigen/src/Core/ArrayWrapper.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		./Eigen/src/Core/Assign_MKL.h \
		./Eigen/src/Core/GlobalFunctions.h \
		./Eigen/src/Core/util/ReenableStupidWarnings.h \
		./Eigen/Eigen2Support \
		./Eigen/src/Eigen2Support/Macros.h \
		./Eigen/src/Eigen2Support/Memory.h \
		./Eigen/src/Eigen2Support/Meta.h \
		./Eigen/src/Eigen2Support/Lazy.h \
		./Eigen/src/Eigen2Support/Cwise.h \
		./Eigen/src/Eigen2Support/CwiseOperators.h \
		./Eigen/src/Eigen2Support/TriangularSolver.h \
		./Eigen/src/Eigen2Support/Block.h \
		./Eigen/src/Eigen2Support/VectorBlock.h \
		./Eigen/src/Eigen2Support/Minor.h \
		./Eigen/src/Eigen2Support/MathFunctions.h \
		./Eigen/LU \
		./Eigen/src/misc/Solve.h \
		./Eigen/src/misc/Kernel.h \
		./Eigen/src/misc/Image.h \
		./Eigen/src/LU/FullPivLU.h \
		./Eigen/src/LU/PartialPivLU.h \
		./Eigen/src/LU/PartialPivLU_MKL.h \
		./Eigen/src/LU/Determinant.h \
		./Eigen/src/LU/Inverse.h \
		./Eigen/src/LU/arch/Inverse_SSE.h \
		./Eigen/src/Eigen2Support/LU.h \
		./Eigen/Cholesky \
		./Eigen/src/Cholesky/LLT.h \
		./Eigen/src/Cholesky/LDLT.h \
		./Eigen/src/Cholesky/LLT_MKL.h \
		./Eigen/QR \
		./Eigen/Jacobi \
		./Eigen/src/Jacobi/Jacobi.h \
		./Eigen/Householder \
		./Eigen/src/Householder/Householder.h \
		./Eigen/src/Householder/HouseholderSequence.h \
		./Eigen/src/Householder/BlockHouseholder.h \
		./Eigen/src/QR/HouseholderQR.h \
		./Eigen/src/QR/FullPivHouseholderQR.h \
		./Eigen/src/QR/ColPivHouseholderQR.h \
		./Eigen/src/QR/HouseholderQR_MKL.h \
		./Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		./Eigen/src/Eigen2Support/QR.h \
		./Eigen/Eigenvalues \
		./Eigen/Geometry \
		./Eigen/SVD \
		./Eigen/src/SVD/JacobiSVD.h \
		./Eigen/src/SVD/JacobiSVD_MKL.h \
		./Eigen/src/SVD/UpperBidiagonalization.h \
		./Eigen/src/Eigen2Support/SVD.h \
		./Eigen/src/Geometry/OrthoMethods.h \
		./Eigen/src/Geometry/EulerAngles.h \
		./Eigen/src/Geometry/Homogeneous.h \
		./Eigen/src/Geometry/RotationBase.h \
		./Eigen/src/Geometry/Rotation2D.h \
		./Eigen/src/Geometry/Quaternion.h \
		./Eigen/src/Geometry/AngleAxis.h \
		./Eigen/src/Geometry/Transform.h \
		./Eigen/src/Geometry/Translation.h \
		./Eigen/src/Geometry/Scaling.h \
		./Eigen/src/Geometry/Hyperplane.h \
		./Eigen/src/Geometry/ParametrizedLine.h \
		./Eigen/src/Geometry/AlignedBox.h \
		./Eigen/src/Geometry/Umeyama.h \
		./Eigen/src/Geometry/arch/Geometry_SSE.h \
		./Eigen/src/Eigen2Support/Geometry/All.h \
		./Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		./Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		./Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		./Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		./Eigen/src/Eigen2Support/Geometry/Transform.h \
		./Eigen/src/Eigen2Support/Geometry/Translation.h \
		./Eigen/src/Eigen2Support/Geometry/Scaling.h \
		./Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		./Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		./Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		./Eigen/src/Eigenvalues/Tridiagonalization.h \
		./Eigen/src/Eigenvalues/RealSchur.h \
		./Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		./Eigen/src/Eigenvalues/EigenSolver.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/ComplexSchur.h \
		./Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		./Eigen/src/Eigenvalues/RealQZ.h \
		./Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		./Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		./Eigen/src/Eigenvalues/RealSchur_MKL.h \
		./Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multilayerperceptron.o ./multilayerperceptron.cpp
