#############################################################################
# Makefile for building: MLP
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  ./MLP.pro
# Template: app
# Command: $(QT)/gcc_64/bin/qmake -spec linux-icc-64 CONFIG+=release -o Makefile ./MLP.pro
#############################################################################

QT            = /home/leonard/Qt/5.5
INTEL         = /opt/intel

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = icc
CXX           = icpc
DEFINES       = -DNDEBUG -DEIGEN_USE_MKL_ALL
CFLAGS        = -falign-functions=16 -ansi-alias -fstrict-aliasing -w1 -Wall -Wcheck -wd1572,873,2259,2261 -fPIC $(DEFINES)
CXXFLAGS      = -fast -march=corei7 -qopenmp -static -falign-functions=16 -ansi-alias -fstrict-aliasing -std=c++0x -w1 -Wall -Wcheck -wd1572,873,2259,2261 -fPIC $(DEFINES)
INCPATH       = -I././MLPDigits -I. -I$PWD/Eigen -I$(INTEL)/mkl/include -I$(QT)/gcc_64/mkspecs/linux-icc-64
QMAKE         = $(QT)/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MLP1.0.0
DISTDIR = /data/Documents/Programmation/Qt/MLPDigits/Build_Release/.tmp/MLP1.0.0
LINK          = icpc
LFLAGS        = -Wl,-rpath,$(QT)/gcc_64
LIBS          = $(SUBLIBS) -L$(INTEL)/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -L/opt/intel/lib/intel64 -liomp5 -lpthread -lm 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ./main.cpp \
		./multilayerperceptron.cpp 
OBJECTS       = main.o \
		multilayerperceptron.o
DIST          = $(QT)/gcc_64/mkspecs/features/spec_pre.prf \
		$(QT)/gcc_64/mkspecs/common/unix.conf \
		$(QT)/gcc_64/mkspecs/common/linux.conf \
		$(QT)/gcc_64/mkspecs/qconfig.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_core.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_help.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_location.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_network.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_script.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		$(QT)/gcc_64/mkspecs/features/qt_functions.prf \
		$(QT)/gcc_64/mkspecs/features/qt_config.prf \
		$(QT)/gcc_64/mkspecs/linux-icc/qmake.conf \
		$(QT)/gcc_64/mkspecs/linux-icc-64/qmake.conf \
		$(QT)/gcc_64/mkspecs/features/spec_post.prf \
		$(QT)/gcc_64/mkspecs/features/exclusive_builds.prf \
		$(QT)/gcc_64/mkspecs/features/default_pre.prf \
		$(QT)/gcc_64/mkspecs/features/resolve_config.prf \
		$(QT)/gcc_64/mkspecs/features/default_post.prf \
		$(QT)/gcc_64/mkspecs/features/c++11.prf \
		$(QT)/gcc_64/mkspecs/features/warn_on.prf \
		$(QT)/gcc_64/mkspecs/features/testcase_targets.prf \
		$(QT)/gcc_64/mkspecs/features/exceptions.prf \
		$(QT)/gcc_64/mkspecs/features/yacc.prf \
		$(QT)/gcc_64/mkspecs/features/lex.prf \
		multilayerperceptron.h \
		io.h \
		includes.h \
                main.cpp \
		multilayerperceptron.cpp
QMAKE_TARGET  = MLP
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MLP


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ./MLP.pro $(QT)/gcc_64/mkspecs/linux-icc-64/qmake.conf /home/leonard/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		$(QT)/gcc_64/mkspecs/common/unix.conf \
		$(QT)/gcc_64/mkspecs/common/linux.conf \
		$(QT)/gcc_64/mkspecs/qconfig.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_core.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_help.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_location.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_network.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_script.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		$(QT)/gcc_64/mkspecs/features/qt_functions.prf \
		$(QT)/gcc_64/mkspecs/features/qt_config.prf \
		$(QT)/gcc_64/mkspecs/linux-icc/qmake.conf \
		$(QT)/gcc_64/mkspecs/linux-icc-64/qmake.conf \
		$(QT)/gcc_64/mkspecs/features/spec_post.prf \
		$(QT)/gcc_64/mkspecs/features/exclusive_builds.prf \
		$(QT)/gcc_64/mkspecs/features/default_pre.prf \
		./deployment.pri \
		$(QT)/gcc_64/mkspecs/features/resolve_config.prf \
		$(QT)/gcc_64/mkspecs/features/default_post.prf \
		$(QT)/gcc_64/mkspecs/features/c++11.prf \
		$(QT)/gcc_64/mkspecs/features/warn_on.prf \
		$(QT)/gcc_64/mkspecs/features/testcase_targets.prf \
		$(QT)/gcc_64/mkspecs/features/exceptions.prf \
		$(QT)/gcc_64/mkspecs/features/yacc.prf \
		$(QT)/gcc_64/mkspecs/features/lex.prf \
		./MLP.pro
	$(QMAKE) -spec linux-icc-64 CONFIG+=release -o Makefile ./MLP.pro
$(QT)/gcc_64/mkspecs/features/spec_pre.prf:
$(QT)/gcc_64/mkspecs/common/unix.conf:
$(QT)/gcc_64/mkspecs/common/linux.conf:
$(QT)/gcc_64/mkspecs/qconfig.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_core.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_designer.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_gui.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_help.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_location.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_network.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qml.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_quick.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_script.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_sql.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_svg.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_xml.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
$(QT)/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
$(QT)/gcc_64/mkspecs/features/qt_functions.prf:
$(QT)/gcc_64/mkspecs/features/qt_config.prf:
$(QT)/gcc_64/mkspecs/linux-icc/qmake.conf:
$(QT)/gcc_64/mkspecs/linux-icc-64/qmake.conf:
$(QT)/gcc_64/mkspecs/features/spec_post.prf:
$(QT)/gcc_64/mkspecs/features/exclusive_builds.prf:
$(QT)/gcc_64/mkspecs/features/default_pre.prf:
./deployment.pri:
$(QT)/gcc_64/mkspecs/features/resolve_config.prf:
$(QT)/gcc_64/mkspecs/features/default_post.prf:
$(QT)/gcc_64/mkspecs/features/c++11.prf:
$(QT)/gcc_64/mkspecs/features/warn_on.prf:
$(QT)/gcc_64/mkspecs/features/testcase_targets.prf:
$(QT)/gcc_64/mkspecs/features/exceptions.prf:
$(QT)/gcc_64/mkspecs/features/yacc.prf:
$(QT)/gcc_64/mkspecs/features/lex.prf:
./MLP.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-icc-64 CONFIG+=release -o Makefile ./MLP.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) -r $(OBJECTS_DIR)/ti_files
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: ./main.cpp ./multilayerperceptron.h \
		./includes.h \
		./Eigen/Dense \
		./Eigen/Core \
		./Eigen/src/Core/util/DisableStupidWarnings.h \
		./Eigen/src/Core/util/Macros.h \
		./Eigen/src/Core/util/MKL_support.h \
		$(INTEL)/mkl/include/mkl.h \
		$(INTEL)/mkl/include/mkl_types.h \
		$(INTEL)/mkl/include/mkl_blas.h \
		$(INTEL)/mkl/include/mkl_trans.h \
		$(INTEL)/mkl/include/mkl_cblas.h \
		$(INTEL)/mkl/include/mkl_spblas.h \
		$(INTEL)/mkl/include/mkl_lapack.h \
		$(INTEL)/mkl/include/mkl_lapacke.h \
		$(INTEL)/mkl/include/mkl_solver.h \
		$(INTEL)/mkl/include/mkl_dss.h \
		$(INTEL)/mkl/include/mkl_pardiso.h \
		$(INTEL)/mkl/include/mkl_sparse_handle.h \
		$(INTEL)/mkl/include/mkl_rci.h \
		$(INTEL)/mkl/include/mkl_service.h \
		$(INTEL)/mkl/include/mkl_vml.h \
		$(INTEL)/mkl/include/mkl_vml_defines.h \
		$(INTEL)/mkl/include/mkl_vml_types.h \
		$(INTEL)/mkl/include/mkl_vml_functions.h \
		$(INTEL)/mkl/include/mkl_vsl.h \
		$(INTEL)/mkl/include/mkl_vsl_defines.h \
		$(INTEL)/mkl/include/mkl_vsl_functions.h \
		$(INTEL)/mkl/include/mkl_vsl_types.h \
		$(INTEL)/mkl/include/mkl_df.h \
		$(INTEL)/mkl/include/mkl_df_defines.h \
		$(INTEL)/mkl/include/mkl_df_functions.h \
		$(INTEL)/mkl/include/mkl_df_types.h \
		$(INTEL)/mkl/include/mkl_dfti.h \
		$(INTEL)/mkl/include/mkl_trig_transforms.h \
		$(INTEL)/mkl/include/mkl_poisson.h \
		$(INTEL)/mkl/include/mkl_solvers_ee.h \
		$(INTEL)/mkl/include/mkl_direct_call.h \
		$(INTEL)/mkl/include/mkl_direct_blas.h \
		./Eigen/src/Core/util/Constants.h \
		./Eigen/src/Core/util/ForwardDeclarations.h \
		./Eigen/src/Core/util/Meta.h \
		./Eigen/src/Core/util/StaticAssert.h \
		./Eigen/src/Core/util/XprHelper.h \
		./Eigen/src/Core/util/Memory.h \
		./Eigen/src/Core/NumTraits.h \
		./Eigen/src/Core/MathFunctions.h \
		./Eigen/src/Core/GenericPacketMath.h \
		./Eigen/src/Core/arch/SSE/PacketMath.h \
		./Eigen/src/Core/arch/SSE/MathFunctions.h \
		./Eigen/src/Core/arch/SSE/Complex.h \
		./Eigen/src/Core/arch/AltiVec/PacketMath.h \
		./Eigen/src/Core/arch/AltiVec/Complex.h \
		./Eigen/src/Core/arch/NEON/PacketMath.h \
		./Eigen/src/Core/arch/NEON/Complex.h \
		./Eigen/src/Core/arch/Default/Settings.h \
		./Eigen/src/Core/Functors.h \
		./Eigen/src/Core/DenseCoeffsBase.h \
		./Eigen/src/Core/DenseBase.h \
		./Eigen/src/plugins/BlockMethods.h \
		./Eigen/src/Core/MatrixBase.h \
		./Eigen/src/plugins/CommonCwiseUnaryOps.h \
		./Eigen/src/plugins/CommonCwiseBinaryOps.h \
		./Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		./Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		./Eigen/src/Core/EigenBase.h \
		./Eigen/src/Core/Assign.h \
		./Eigen/src/Core/util/BlasUtil.h \
		./Eigen/src/Core/DenseStorage.h \
		./Eigen/src/Core/NestByValue.h \
		./Eigen/src/Core/ForceAlignedAccess.h \
		./Eigen/src/Core/ReturnByValue.h \
		./Eigen/src/Core/NoAlias.h \
		./Eigen/src/Core/PlainObjectBase.h \
		./Eigen/src/Core/Matrix.h \
		./Eigen/src/Core/Array.h \
		./Eigen/src/Core/CwiseBinaryOp.h \
		./Eigen/src/Core/CwiseUnaryOp.h \
		./Eigen/src/Core/CwiseNullaryOp.h \
		./Eigen/src/Core/CwiseUnaryView.h \
		./Eigen/src/Core/SelfCwiseBinaryOp.h \
		./Eigen/src/Core/Dot.h \
		./Eigen/src/Core/StableNorm.h \
		./Eigen/src/Core/MapBase.h \
		./Eigen/src/Core/Stride.h \
		./Eigen/src/Core/Map.h \
		./Eigen/src/Core/Block.h \
		./Eigen/src/Core/VectorBlock.h \
		./Eigen/src/Core/Ref.h \
		./Eigen/src/Core/Transpose.h \
		./Eigen/src/Core/DiagonalMatrix.h \
		./Eigen/src/Core/Diagonal.h \
		./Eigen/src/Core/DiagonalProduct.h \
		./Eigen/src/Core/PermutationMatrix.h \
		./Eigen/src/Core/Transpositions.h \
		./Eigen/src/Core/Redux.h \
		./Eigen/src/Core/Visitor.h \
		./Eigen/src/Core/Fuzzy.h \
		./Eigen/src/Core/IO.h \
		./Eigen/src/Core/Swap.h \
		./Eigen/src/Core/CommaInitializer.h \
		./Eigen/src/Core/Flagged.h \
		./Eigen/src/Core/ProductBase.h \
		./Eigen/src/Core/GeneralProduct.h \
		./Eigen/src/Core/TriangularMatrix.h \
		./Eigen/src/Core/SelfAdjointView.h \
		./Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		./Eigen/src/Core/products/Parallelizer.h \
		./Eigen/src/Core/products/CoeffBasedProduct.h \
		./Eigen/src/Core/products/GeneralMatrixVector.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix.h \
		./Eigen/src/Core/SolveTriangular.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		./Eigen/src/Core/products/SelfadjointProduct.h \
		./Eigen/src/Core/products/SelfadjointRank2Update.h \
		./Eigen/src/Core/products/TriangularMatrixVector.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix.h \
		./Eigen/src/Core/products/TriangularSolverMatrix.h \
		./Eigen/src/Core/products/TriangularSolverVector.h \
		./Eigen/src/Core/BandMatrix.h \
		./Eigen/src/Core/CoreIterators.h \
		./Eigen/src/Core/BooleanRedux.h \
		./Eigen/src/Core/Select.h \
		./Eigen/src/Core/VectorwiseOp.h \
		./Eigen/src/Core/Random.h \
		./Eigen/src/Core/Replicate.h \
		./Eigen/src/Core/Reverse.h \
		./Eigen/src/Core/ArrayBase.h \
		./Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		./Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		./Eigen/src/Core/ArrayWrapper.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		./Eigen/src/Core/Assign_MKL.h \
		./Eigen/src/Core/GlobalFunctions.h \
		./Eigen/src/Core/util/ReenableStupidWarnings.h \
		./Eigen/Eigen2Support \
		./Eigen/src/Eigen2Support/Macros.h \
		./Eigen/src/Eigen2Support/Memory.h \
		./Eigen/src/Eigen2Support/Meta.h \
		./Eigen/src/Eigen2Support/Lazy.h \
		./Eigen/src/Eigen2Support/Cwise.h \
		./Eigen/src/Eigen2Support/CwiseOperators.h \
		./Eigen/src/Eigen2Support/TriangularSolver.h \
		./Eigen/src/Eigen2Support/Block.h \
		./Eigen/src/Eigen2Support/VectorBlock.h \
		./Eigen/src/Eigen2Support/Minor.h \
		./Eigen/src/Eigen2Support/MathFunctions.h \
		./Eigen/LU \
		./Eigen/src/misc/Solve.h \
		./Eigen/src/misc/Kernel.h \
		./Eigen/src/misc/Image.h \
		./Eigen/src/LU/FullPivLU.h \
		./Eigen/src/LU/PartialPivLU.h \
		./Eigen/src/LU/PartialPivLU_MKL.h \
		./Eigen/src/LU/Determinant.h \
		./Eigen/src/LU/Inverse.h \
		./Eigen/src/LU/arch/Inverse_SSE.h \
		./Eigen/src/Eigen2Support/LU.h \
		./Eigen/Cholesky \
		./Eigen/src/Cholesky/LLT.h \
		./Eigen/src/Cholesky/LDLT.h \
		./Eigen/src/Cholesky/LLT_MKL.h \
		./Eigen/QR \
		./Eigen/Jacobi \
		./Eigen/src/Jacobi/Jacobi.h \
		./Eigen/Householder \
		./Eigen/src/Householder/Householder.h \
		./Eigen/src/Householder/HouseholderSequence.h \
		./Eigen/src/Householder/BlockHouseholder.h \
		./Eigen/src/QR/HouseholderQR.h \
		./Eigen/src/QR/FullPivHouseholderQR.h \
		./Eigen/src/QR/ColPivHouseholderQR.h \
		./Eigen/src/QR/HouseholderQR_MKL.h \
		./Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		./Eigen/src/Eigen2Support/QR.h \
		./Eigen/Eigenvalues \
		./Eigen/Geometry \
		./Eigen/SVD \
		./Eigen/src/SVD/JacobiSVD.h \
		./Eigen/src/SVD/JacobiSVD_MKL.h \
		./Eigen/src/SVD/UpperBidiagonalization.h \
		./Eigen/src/Eigen2Support/SVD.h \
		./Eigen/src/Geometry/OrthoMethods.h \
		./Eigen/src/Geometry/EulerAngles.h \
		./Eigen/src/Geometry/Homogeneous.h \
		./Eigen/src/Geometry/RotationBase.h \
		./Eigen/src/Geometry/Rotation2D.h \
		./Eigen/src/Geometry/Quaternion.h \
		./Eigen/src/Geometry/AngleAxis.h \
		./Eigen/src/Geometry/Transform.h \
		./Eigen/src/Geometry/Translation.h \
		./Eigen/src/Geometry/Scaling.h \
		./Eigen/src/Geometry/Hyperplane.h \
		./Eigen/src/Geometry/ParametrizedLine.h \
		./Eigen/src/Geometry/AlignedBox.h \
		./Eigen/src/Geometry/Umeyama.h \
		./Eigen/src/Geometry/arch/Geometry_SSE.h \
		./Eigen/src/Eigen2Support/Geometry/All.h \
		./Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		./Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		./Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		./Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		./Eigen/src/Eigen2Support/Geometry/Transform.h \
		./Eigen/src/Eigen2Support/Geometry/Translation.h \
		./Eigen/src/Eigen2Support/Geometry/Scaling.h \
		./Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		./Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		./Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		./Eigen/src/Eigenvalues/Tridiagonalization.h \
		./Eigen/src/Eigenvalues/RealSchur.h \
		./Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		./Eigen/src/Eigenvalues/EigenSolver.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/ComplexSchur.h \
		./Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		./Eigen/src/Eigenvalues/RealQZ.h \
		./Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		./Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		./Eigen/src/Eigenvalues/RealSchur_MKL.h \
		./Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h \
		./io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ./main.cpp

multilayerperceptron.o: ./multilayerperceptron.cpp ./multilayerperceptron.h \
		./includes.h \
		./Eigen/Dense \
		./Eigen/Core \
		./Eigen/src/Core/util/DisableStupidWarnings.h \
		./Eigen/src/Core/util/Macros.h \
		./Eigen/src/Core/util/MKL_support.h \
		$(INTEL)/mkl/include/mkl.h \
		$(INTEL)/mkl/include/mkl_types.h \
		$(INTEL)/mkl/include/mkl_blas.h \
		$(INTEL)/mkl/include/mkl_trans.h \
		$(INTEL)/mkl/include/mkl_cblas.h \
		$(INTEL)/mkl/include/mkl_spblas.h \
		$(INTEL)/mkl/include/mkl_lapack.h \
		$(INTEL)/mkl/include/mkl_lapacke.h \
		$(INTEL)/mkl/include/mkl_solver.h \
		$(INTEL)/mkl/include/mkl_dss.h \
		$(INTEL)/mkl/include/mkl_pardiso.h \
		$(INTEL)/mkl/include/mkl_sparse_handle.h \
		$(INTEL)/mkl/include/mkl_rci.h \
		$(INTEL)/mkl/include/mkl_service.h \
		$(INTEL)/mkl/include/mkl_vml.h \
		$(INTEL)/mkl/include/mkl_vml_defines.h \
		$(INTEL)/mkl/include/mkl_vml_types.h \
		$(INTEL)/mkl/include/mkl_vml_functions.h \
		$(INTEL)/mkl/include/mkl_vsl.h \
		$(INTEL)/mkl/include/mkl_vsl_defines.h \
		$(INTEL)/mkl/include/mkl_vsl_functions.h \
		$(INTEL)/mkl/include/mkl_vsl_types.h \
		$(INTEL)/mkl/include/mkl_df.h \
		$(INTEL)/mkl/include/mkl_df_defines.h \
		$(INTEL)/mkl/include/mkl_df_functions.h \
		$(INTEL)/mkl/include/mkl_df_types.h \
		$(INTEL)/mkl/include/mkl_dfti.h \
		$(INTEL)/mkl/include/mkl_trig_transforms.h \
		$(INTEL)/mkl/include/mkl_poisson.h \
		$(INTEL)/mkl/include/mkl_solvers_ee.h \
		$(INTEL)/mkl/include/mkl_direct_call.h \
		$(INTEL)/mkl/include/mkl_direct_blas.h \
		./Eigen/src/Core/util/Constants.h \
		./Eigen/src/Core/util/ForwardDeclarations.h \
		./Eigen/src/Core/util/Meta.h \
		./Eigen/src/Core/util/StaticAssert.h \
		./Eigen/src/Core/util/XprHelper.h \
		./Eigen/src/Core/util/Memory.h \
		./Eigen/src/Core/NumTraits.h \
		./Eigen/src/Core/MathFunctions.h \
		./Eigen/src/Core/GenericPacketMath.h \
		./Eigen/src/Core/arch/SSE/PacketMath.h \
		./Eigen/src/Core/arch/SSE/MathFunctions.h \
		./Eigen/src/Core/arch/SSE/Complex.h \
		./Eigen/src/Core/arch/AltiVec/PacketMath.h \
		./Eigen/src/Core/arch/AltiVec/Complex.h \
		./Eigen/src/Core/arch/NEON/PacketMath.h \
		./Eigen/src/Core/arch/NEON/Complex.h \
		./Eigen/src/Core/arch/Default/Settings.h \
		./Eigen/src/Core/Functors.h \
		./Eigen/src/Core/DenseCoeffsBase.h \
		./Eigen/src/Core/DenseBase.h \
		./Eigen/src/plugins/BlockMethods.h \
		./Eigen/src/Core/MatrixBase.h \
		./Eigen/src/plugins/CommonCwiseUnaryOps.h \
		./Eigen/src/plugins/CommonCwiseBinaryOps.h \
		./Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		./Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		./Eigen/src/Core/EigenBase.h \
		./Eigen/src/Core/Assign.h \
		./Eigen/src/Core/util/BlasUtil.h \
		./Eigen/src/Core/DenseStorage.h \
		./Eigen/src/Core/NestByValue.h \
		./Eigen/src/Core/ForceAlignedAccess.h \
		./Eigen/src/Core/ReturnByValue.h \
		./Eigen/src/Core/NoAlias.h \
		./Eigen/src/Core/PlainObjectBase.h \
		./Eigen/src/Core/Matrix.h \
		./Eigen/src/Core/Array.h \
		./Eigen/src/Core/CwiseBinaryOp.h \
		./Eigen/src/Core/CwiseUnaryOp.h \
		./Eigen/src/Core/CwiseNullaryOp.h \
		./Eigen/src/Core/CwiseUnaryView.h \
		./Eigen/src/Core/SelfCwiseBinaryOp.h \
		./Eigen/src/Core/Dot.h \
		./Eigen/src/Core/StableNorm.h \
		./Eigen/src/Core/MapBase.h \
		./Eigen/src/Core/Stride.h \
		./Eigen/src/Core/Map.h \
		./Eigen/src/Core/Block.h \
		./Eigen/src/Core/VectorBlock.h \
		./Eigen/src/Core/Ref.h \
		./Eigen/src/Core/Transpose.h \
		./Eigen/src/Core/DiagonalMatrix.h \
		./Eigen/src/Core/Diagonal.h \
		./Eigen/src/Core/DiagonalProduct.h \
		./Eigen/src/Core/PermutationMatrix.h \
		./Eigen/src/Core/Transpositions.h \
		./Eigen/src/Core/Redux.h \
		./Eigen/src/Core/Visitor.h \
		./Eigen/src/Core/Fuzzy.h \
		./Eigen/src/Core/IO.h \
		./Eigen/src/Core/Swap.h \
		./Eigen/src/Core/CommaInitializer.h \
		./Eigen/src/Core/Flagged.h \
		./Eigen/src/Core/ProductBase.h \
		./Eigen/src/Core/GeneralProduct.h \
		./Eigen/src/Core/TriangularMatrix.h \
		./Eigen/src/Core/SelfAdjointView.h \
		./Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		./Eigen/src/Core/products/Parallelizer.h \
		./Eigen/src/Core/products/CoeffBasedProduct.h \
		./Eigen/src/Core/products/GeneralMatrixVector.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix.h \
		./Eigen/src/Core/SolveTriangular.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		./Eigen/src/Core/products/SelfadjointProduct.h \
		./Eigen/src/Core/products/SelfadjointRank2Update.h \
		./Eigen/src/Core/products/TriangularMatrixVector.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix.h \
		./Eigen/src/Core/products/TriangularSolverMatrix.h \
		./Eigen/src/Core/products/TriangularSolverVector.h \
		./Eigen/src/Core/BandMatrix.h \
		./Eigen/src/Core/CoreIterators.h \
		./Eigen/src/Core/BooleanRedux.h \
		./Eigen/src/Core/Select.h \
		./Eigen/src/Core/VectorwiseOp.h \
		./Eigen/src/Core/Random.h \
		./Eigen/src/Core/Replicate.h \
		./Eigen/src/Core/Reverse.h \
		./Eigen/src/Core/ArrayBase.h \
		./Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		./Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		./Eigen/src/Core/ArrayWrapper.h \
		./Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		./Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		./Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		./Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		./Eigen/src/Core/Assign_MKL.h \
		./Eigen/src/Core/GlobalFunctions.h \
		./Eigen/src/Core/util/ReenableStupidWarnings.h \
		./Eigen/Eigen2Support \
		./Eigen/src/Eigen2Support/Macros.h \
		./Eigen/src/Eigen2Support/Memory.h \
		./Eigen/src/Eigen2Support/Meta.h \
		./Eigen/src/Eigen2Support/Lazy.h \
		./Eigen/src/Eigen2Support/Cwise.h \
		./Eigen/src/Eigen2Support/CwiseOperators.h \
		./Eigen/src/Eigen2Support/TriangularSolver.h \
		./Eigen/src/Eigen2Support/Block.h \
		./Eigen/src/Eigen2Support/VectorBlock.h \
		./Eigen/src/Eigen2Support/Minor.h \
		./Eigen/src/Eigen2Support/MathFunctions.h \
		./Eigen/LU \
		./Eigen/src/misc/Solve.h \
		./Eigen/src/misc/Kernel.h \
		./Eigen/src/misc/Image.h \
		./Eigen/src/LU/FullPivLU.h \
		./Eigen/src/LU/PartialPivLU.h \
		./Eigen/src/LU/PartialPivLU_MKL.h \
		./Eigen/src/LU/Determinant.h \
		./Eigen/src/LU/Inverse.h \
		./Eigen/src/LU/arch/Inverse_SSE.h \
		./Eigen/src/Eigen2Support/LU.h \
		./Eigen/Cholesky \
		./Eigen/src/Cholesky/LLT.h \
		./Eigen/src/Cholesky/LDLT.h \
		./Eigen/src/Cholesky/LLT_MKL.h \
		./Eigen/QR \
		./Eigen/Jacobi \
		./Eigen/src/Jacobi/Jacobi.h \
		./Eigen/Householder \
		./Eigen/src/Householder/Householder.h \
		./Eigen/src/Householder/HouseholderSequence.h \
		./Eigen/src/Householder/BlockHouseholder.h \
		./Eigen/src/QR/HouseholderQR.h \
		./Eigen/src/QR/FullPivHouseholderQR.h \
		./Eigen/src/QR/ColPivHouseholderQR.h \
		./Eigen/src/QR/HouseholderQR_MKL.h \
		./Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		./Eigen/src/Eigen2Support/QR.h \
		./Eigen/Eigenvalues \
		./Eigen/Geometry \
		./Eigen/SVD \
		./Eigen/src/SVD/JacobiSVD.h \
		./Eigen/src/SVD/JacobiSVD_MKL.h \
		./Eigen/src/SVD/UpperBidiagonalization.h \
		./Eigen/src/Eigen2Support/SVD.h \
		./Eigen/src/Geometry/OrthoMethods.h \
		./Eigen/src/Geometry/EulerAngles.h \
		./Eigen/src/Geometry/Homogeneous.h \
		./Eigen/src/Geometry/RotationBase.h \
		./Eigen/src/Geometry/Rotation2D.h \
		./Eigen/src/Geometry/Quaternion.h \
		./Eigen/src/Geometry/AngleAxis.h \
		./Eigen/src/Geometry/Transform.h \
		./Eigen/src/Geometry/Translation.h \
		./Eigen/src/Geometry/Scaling.h \
		./Eigen/src/Geometry/Hyperplane.h \
		./Eigen/src/Geometry/ParametrizedLine.h \
		./Eigen/src/Geometry/AlignedBox.h \
		./Eigen/src/Geometry/Umeyama.h \
		./Eigen/src/Geometry/arch/Geometry_SSE.h \
		./Eigen/src/Eigen2Support/Geometry/All.h \
		./Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		./Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		./Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		./Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		./Eigen/src/Eigen2Support/Geometry/Transform.h \
		./Eigen/src/Eigen2Support/Geometry/Translation.h \
		./Eigen/src/Eigen2Support/Geometry/Scaling.h \
		./Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		./Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		./Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		./Eigen/src/Eigenvalues/Tridiagonalization.h \
		./Eigen/src/Eigenvalues/RealSchur.h \
		./Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		./Eigen/src/Eigenvalues/EigenSolver.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		./Eigen/src/Eigenvalues/ComplexSchur.h \
		./Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		./Eigen/src/Eigenvalues/RealQZ.h \
		./Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		./Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		./Eigen/src/Eigenvalues/RealSchur_MKL.h \
		./Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		./Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multilayerperceptron.o ./multilayerperceptron.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/MLP/bin || mkdir -p $(INSTALL_ROOT)/opt/MLP/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/MLP/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/MLP/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/MLP/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/MLP/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

